CREATE TABLE IF NOT EXISTS profiles(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
	description text,
	active boolean NOT NULL DEFAULT FALSE,
   	updateddate timestamp,
    createddate timestamp NOT NULL
);

INSERT INTO profiles (name, description, active, createddate)
VALUES ('Administrador', 'Administrador del Sistema', TRUE, CURRENT_TIMESTAMP);

INSERT INTO profiles (name, description, active, createddate)
VALUES ('Entrenador', 'Perfil del Entrenador', TRUE, CURRENT_TIMESTAMP);

INSERT INTO profiles (name, description, active, createddate)
VALUES ('Atleta', 'Perfil del Atleta', TRUE, CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
	password text NOT NULL CHECK (password <> ''),
	fullname text NOT NULL CHECK (fullname <> ''),
	email text NOT NULL CHECK (email <> ''),
    idProfile integer NOT NULL REFERENCES profiles(id),
	active boolean NOT NULL DEFAULT FALSE,
   	updateddate timestamp,
    createddate timestamp NOT NULL
);

INSERT INTO users (name, password, fullname, email, idProfile, active, createddate)
VALUES ('admin', '$2a$10$RtmjRYFJkMkY3HpfK9UkNuu/6S9aKkP0t4vYDVP/0ZSekDgjhg61C', 'Administrador', 'admin@mail.com', 1, TRUE, CURRENT_TIMESTAMP);
